---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: groundhog2k
  namespace: instavote
spec:
  interval: 1m0s
  provider: generic
  timeout: 1m0s
  url: https://groundhog2k.github.io/helm-charts

