---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: db
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgres
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
      version: 0.2.9
  interval: 1m0s
  targetNamespace: instavote
  values:
    fullnameOverride: db
    settings:
      authMethod: trust

