apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-helmrelease.yaml
- db-helmrepository.yaml
- github-provider.yaml
- instavote-source.yaml
- monitoring-config.yaml
- monitoring-kube-prometheus-stack.yaml
- monitoring-source.yaml
- redis-alert.yaml
- redis-staging-ks.yaml
- result-helmrelease.yaml
- result-img-policy.yaml
- result-img-repo.yaml
- result-img-update.yaml
- slack-alert.yaml
- slack-provider.yaml
- vote-alert.yaml
- vote-img-policy.yaml
- vote-img-repo.yaml
- vote-img-update.yaml
- vote-staging-ks.yaml
- webhook-receiver.yaml
- worker-alert.yaml
- worker-staging-ks.yaml
