---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: worker-staging
  namespace: instavote
spec:
  interval: 1m0s
  path: ./kustomize/worker/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: instavote

